
# 2025-04-07 - refactor: Convert Pulumi to TypeScript
apiVersion: monitoring.coreos.com/v1
kind: Rollout
metadata:
  name: frontend
spec:
  hosts:
  - "web.staging.example.com"
# 2025-04-07 - feat: Implement blue-green deployments
apiVersion: monitoring.coreos.com/v1
kind: Rollout
metadata:
  name: frontend
spec:
  hosts:
  - "web.staging.example.com"
# 2025-04-07 - refactor: Simplify Kubernetes manifests
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: paymentservice
spec:
  hosts:
  - "web.staging.example.com"
# 2025-04-07 - docs: Update disaster recovery plan
apiVersion: monitoring.coreos.com/v1
kind: Rollout
metadata:
  name: paymentservice
spec:
  replicas: 3
# 2025-04-07 - feat(security): Add OPA gatekeeper policies
apiVersion: networking.istio.io/v1beta1
kind: Rollout
metadata:
  name: monitoring
spec:
  hosts:
  - "web.staging.example.com"
# 2025-04-07 - docs: Add architecture diagrams
apiVersion: networking.istio.io/v1beta1
kind: Prometheus
metadata:
  name: monitoring
spec:
  scrapeInterval: 2m
# 2025-04-07 - chore: Upgrade Istio to 1.18.2
apiVersion: monitoring.coreos.com/v1
kind: Rollout
metadata:
  name: monitoring
spec:
  scrapeInterval: 2m